//! build.rs – compiles the bundled cmark-gfm C library when the
//! `cmark-gfm-ffi` feature is enabled.

fn main() {
    #[cfg(feature = "cmark-gfm-ffi")]
    compile_cmark_gfm();
}

#[cfg(feature = "cmark-gfm-ffi")]
fn compile_cmark_gfm() {
    use std::path::PathBuf;

    // ── locate repository root (two levels up from the linter/ crate) ──────
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .expect("linter/ must have a parent directory");

    let src_dir = repo_root.join("src");
    let ext_dir = repo_root.join("extensions");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // ── emit generated headers that cmake would normally produce ────────────
    write_export_header(&out_dir);
    write_version_header(&out_dir);
    write_config_header(&out_dir);

    // ── core C sources (exclude main.c which defines its own main()) ────────
    let core_sources: &[&str] = &[
        "arena.c",
        "blocks.c",
        "buffer.c",
        "cmark.c",
        "cmark_ctype.c",
        "commonmark.c",
        "footnotes.c",
        "houdini_href_e.c",
        "houdini_html_e.c",
        "houdini_html_u.c",
        "html.c",
        "inlines.c",
        "iterator.c",
        "latex.c",
        "linked_list.c",
        "man.c",
        "map.c",
        "node.c",
        "plaintext.c",
        "plugin.c",
        "references.c",
        "registry.c",
        "render.c",
        "scanners.c",
        "syntax_extension.c",
        "utf8.c",
        "xml.c",
    ];

    // ── GFM extension C sources ─────────────────────────────────────────────
    let ext_sources: &[&str] = &[
        "autolink.c",
        "core-extensions.c",
        "ext_scanners.c",
        "strikethrough.c",
        "table.c",
        "tagfilter.c",
        "tasklist.c",
    ];

    let mut build = cc::Build::new();
    build
        .warnings(false)
        // include paths: generated headers first, then the two source dirs
        .include(&out_dir)
        .include(&src_dir)
        .include(&ext_dir)
        // suppress symbol-visibility attributes – we link statically
        .define("CMARK_GFM_STATIC_DEFINE", None);

    for name in core_sources {
        build.file(src_dir.join(name));
    }
    for name in ext_sources {
        build.file(ext_dir.join(name));
    }

    build.compile("cmark_gfm_bundled");

    // tell cargo to re-run if any C source changes
    println!("cargo:rerun-if-changed={}", src_dir.display());
    println!("cargo:rerun-if-changed={}", ext_dir.display());
}

/// Emits a minimal `cmark-gfm_export.h` that cmake's `generate_export_header`
/// would normally produce.  For a static build all visibility macros are empty.
#[cfg(feature = "cmark-gfm-ffi")]
fn write_export_header(out_dir: &std::path::Path) {
    let content = r#"/* generated by build.rs – static build, no visibility attributes needed */
#ifndef CMARK_GFM_EXPORT_H
#define CMARK_GFM_EXPORT_H

#define CMARK_GFM_EXPORT
#define CMARK_GFM_NO_EXPORT
#define CMARK_GFM_DEPRECATED
#define CMARK_GFM_DEPRECATED_EXPORT
#define CMARK_GFM_DEPRECATED_NO_EXPORT
#define CMARK_GFM_STATIC_DEFINE

#endif /* CMARK_GFM_EXPORT_H */
"#;
    std::fs::write(out_dir.join("cmark-gfm_export.h"), content).unwrap();
}

/// Emits `cmark-gfm_version.h` with version 0.29.0.gfm.13.
#[cfg(feature = "cmark-gfm-ffi")]
fn write_version_header(out_dir: &std::path::Path) {
    let content = r#"/* generated by build.rs */
#ifndef CMARK_GFM_VERSION_H
#define CMARK_GFM_VERSION_H

#define CMARK_GFM_VERSION ((0 << 24) | (29 << 16) | (0 << 8) | 13)
#define CMARK_GFM_VERSION_STRING "0.29.0.gfm.13"

#endif /* CMARK_GFM_VERSION_H */
"#;
    std::fs::write(out_dir.join("cmark-gfm_version.h"), content).unwrap();
}

/// Emits `config.h` derived from config.h.in with Linux/GCC defaults.
#[cfg(feature = "cmark-gfm-ffi")]
fn write_config_header(out_dir: &std::path::Path) {
    let content = r#"/* generated by build.rs */
#ifndef CMARK_CONFIG_H
#define CMARK_CONFIG_H

#define HAVE_STDBOOL_H 1
#define HAVE___BUILTIN_EXPECT 1
#define HAVE___ATTRIBUTE__ 1

#include <stdbool.h>

#define CMARK_ATTRIBUTE(list) __attribute__ (list)

#ifndef CMARK_INLINE
#  define CMARK_INLINE inline
#endif

#endif /* CMARK_CONFIG_H */
"#;
    std::fs::write(out_dir.join("config.h"), content).unwrap();
}
